### ISSUE TITLE
Address.signed_tx() returns false

### ISSUE THREAD

**Issue by katharine-murphy** [fetchai/ledger#1005]
Code to verify an `Address` returns false.

```
function main()

    var account = Address("AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+Pw==");
    var verified : Bool;
    verified = account.signed_tx();
    print(toString(verified));

endfunction
```

**Comment by katharine-murphy** [comment]
Updating: version v0.4.1-rc5

var account = Address("2ifr5dSFRAnXexBMC3HYEVp3JHSuz7KBPXWDRBV4xdFrqGy6R9");
    var verified : Bool;
    verified = account.signedTx();
    print(toString(verified));


Katharines-MBP:vm-lang katharinemurphy$ ./vm-lang ./tests/test.etch 
 F E ╱     vm-lang v0.5.0-alpha7
   T C     Copyright 2018-2019 (c) Fetch AI Ltd.
     H     

false

**Comment by ejfitzgerald** [comment]
This is expected behaviour @katharine-murphy . This can't be easily tested in this way. It will only be true in the context of `@action`
