### ISSUE TITLE
Testing a boolean value in while loops does not work

### ISSUE THREAD

**Issue by katharine-murphy** [fetchai/ledger#1049]
While loops are not working with boolean value checks:
  
Example:
```
while(more_swaps == true)
      ...
endwhile
```
Result:
```
Failed to compile:
line 5: error: operator not supported
```

This error does not occur if doing a test on an integer.
This error may be related to #1007

**Comment by robertdickson** [comment]
This is same bug as issue #1007. Fixed in #1050.
