### ISSUE TITLE
Possible bug: state var assigned and not explicitly .set() usable but not globally persistent

### ISSUE THREAD

**Issue by CobrasCobras** [fetchai/ledger#1073]
From developer slack user. Surrounding editorial is:

>Here's another one (not sure if this is a bug):
>when the value of a state var is only assigned and not explicitly .set() it is locally useable, but not globally persistent (see test2() getting different value).
>At least docu does not state this. And I think this might lead to much lost money in contracts and would suggest assigned values should be persistent (globally)

Issue could be documentation related. 

[stateSet.txt](https://github.com/uvue-git/fetch-ledger/files/3231475/stateSet.txt)

**Comment by pbukva** [comment]
This is true.

Explicit usage of `Set(...)` method ideologically maps to concept generally known as transaction `commit`, thus in the current state of affairs one has to call `Set(...)` to actually commit the value to storage.

It is hard to say whether the `commit` concept was original intent, or the current behaviour is simply a bug (it feels as bug given the fact that `Set(...)` method enforces presence of input parameter).

**Comment by katharine-murphy** [comment]
I have been looking at this today. This code snippet might be useful.

```
function main()

  var myState = State<Int32>("balance", 0);
  // 1. print empty state
  print("1: ");
  printLn(toString(myState.get()));

  // 2. change state inside main
  myState.set(33);
  print("2: ");
  printLn(toString(myState.get()));

  change_state(myState);
  // 3. print state after change_state call
  print("3: ");
  printLn(toString(myState.get()));

  var result = query();
  // 4. print state after query call - notice how query function doesn't change state of the original
  print("4: ");
  printLn(toString(result));

  // 5. alter comments in query method to see that state value is not alterable even though
  // accessible from another function
  // print("5: ");
  // printLn(toString(result)); - returns 55
// printLn(toString(myState.get())); - returns 100

endfunction



function change_state(state : State<Int32>)

  // you can pass around a State parameter and get access to the original state
  var newState = state;
  newState.set(100);

  // but notice that creating a new local state with the same key string does not change the original
  var anotherState = State<Int32>("balance", 42);

endfunction



function query() : Int32

  // HOWEVER, notice that creating a new state with the original key accesses the original state
  var myState = State<Int32>("balance", 0);

  // 4. and returns it, this returns 100!
  return myState.get();

  // 5. 
  // BUT if you set a new variable into the state, it will return the new variable but not 
  // alter the state!!
  // myState.set(55);
  // return myState.get();


endfunction
```
