### ISSUE TITLE
Optimize TensorSlice usage

### ISSUE THREAD

**Issue by MissingNO57** [fetchai/ledger#1090]
I can't easily feed graph with Slice of Tensor.
The only way around is to create Tensor from Slice which is inefficient.

example:
auto cur_input = data.Slice(step).Copy();
graph_->SetInput(input_node_name_, cur_input);

**Comment by troels-im** [comment]
You should use `TensorView` instead. It is in a PR at the moment, but will hopefully be in the code base before long.
