### ISSUE TITLE
Specify Memory Requirements

### ISSUE THREAD

**Issue by Genysys** [fetchai/ledger#1137]
Problem: Unable to build image with docker.

Description:

Docker adding docker images to a repo solves the issue of cross device compatibility. I was trying to build an image for the latest ubuntu image , but could not, even with reallocating 12 GB of memory to the process.

I have eventually had to get the biggest Azure CPU with 256 GB to build it (I know its over kill). 

Would be helpful if there were some guidelines on this.

**Comment by ejfitzgerald** [comment]
Hi,

Sorry to here you are having issues building the ledger. We have seen this issue from time to time. When we have seen this before it was an issue with `make` not detecting the number of CPUs on the system and spinning up a large number of jobs. Can you try the following:

`make -j 4 constellation`

This would limit the build to 4 concurrent jobs.

Hope that helps
