### ISSUE TITLE
VM segfault

### ISSUE THREAD

**Issue by wkaluza** [fetchai/ledger#1168]
The following script causes `vm-lang` and `VmTestToolkit` to segfault. Identified by @dHonerkamp.

```
function main()
  var default_array = Array<Array<UInt64>>(2);
  var bids = State<Array<Array<UInt64>>>("blub", default_array);
endfunction
```

**Comment by robertdickson** [comment]
This is caused by trying to serlalise an Array with null elements.

**Comment by pbukva** [comment]
Fix is prepared, finishing of utests. PR will be available by end of today.
