### ISSUE TITLE
Unify math sqrt tests

### ISSUE THREAD

**Issue by evsmithx** [fetchai/ledger#1195]
Math sqrt tests currently have some separate tests for floating-point types and fixed-point types because the fixed-point sqrt implementation throws a runtime error when a NaN is encountered. Once this has been changed then the tests should be unified.

**Comment by markos** [comment]
Exception throwing is now removed from FixedPoint class, in #1244 . However, we should provide common isNaN/etc wrapper functions for both float/double/FixedPoint types in order to unify the tests.
