### ISSUE TITLE
getBlockNumber() always returns 0

### ISSUE THREAD

**Issue by theoturner** [fetchai/ledger#1202]
Etch: `getBlockNumber()` always returns 0.

Simple contract example:
```java
@query
function blocknum() : UInt64
    var x = getBlockNumber();
    return x;
endfunction
```
This deploys to chain without issue.

When called with `ledger-api-py` as in the [examples](https://github.com/fetchai/ledger-api-py/blob/75943dcc880e8a4326247044d8ee8073135b5c90/examples/contracts.py#L60):
```python
contract.query(api, 'blocknum')
```
This always prints 0. In the ledger log I can see the block number going up under BlockCoordinator info.

**Comment by ejfitzgerald** [comment]
So the `getBlockNumber()` functionality is only supported in transaction (`@action`) handlers currently. This would be a fairly simple addition to make this additionally available in `@query` handlers also.

For context can you describe the use case that you are thinking about?

**Comment by wkaluza** [comment]
The reported behaviour is expected; at the moment we are not supporting this use case.
