### ISSUE TITLE
Overloaded functions for initialisers fails.

### ISSUE THREAD

**Issue by troels-im** [fetchai/ledger#1203]
When creating contacts:

This code fails:
```
@init
function createSupply(owner: Address)
  createSupply(owner, UInt256(12619924713u64));
endfunction

function createSupply(owner: Address, supply: UInt256)
  var supply_state = State< UInt256 >("total_supply");  
  supply_state.set(supply);

  var balance_state = State< UInt256 >(owner);
  balance_state.set( supply );
endfunction
```
This code does not:
```
@init
function createSupply(owner: Address)
  createSupply2(owner, UInt256(12619924713u64));
endfunction

function createSupply2(owner: Address, supply: UInt256)
  var supply_state = State< UInt256 >("total_supply");  
  supply_state.set(supply);

  var balance_state = State< UInt256 >(owner);
  balance_state.set( supply );
endfunction
```

**Comment by pbukva** [comment]
The issue here is that function overload is defined after the point where it is actually called.
Our etch compiler does not seem to do forward code analysis to identify that function with that specific signature is defined later in the code.

For now, defining function before its usage is ought to work:
```cpp
function createSupply(owner: Address, supply: UInt256)
  var supply_state = State< UInt256 >("total_supply");  
  supply_state.set(supply);

  var balance_state = State< UInt256 >(owner);
  balance_state.set( supply );
endfunction

@init
function createSupply(owner: Address)
  createSupply(owner, UInt256(12619924713u64));
endfunction
```

**Comment by robertdickson** [comment]
Prototypes are scanned first, before the bodies of functions are processed, and the compiler should handle both forward declaration and overloaded functions just fine. If not, it is a bug. I will investigate.

**Comment by robertdickson** [comment]
This isn't an etch compiler bug -- the compiler does in fact build multiple overloaded functions. What seems to be happening is that the parameter pack version of VM::Execute() is simply choosing the last overloaded function in the Executable that has the same matching name, which may not be the one you are after, depending on the order of function declaration.

**Comment by robertdickson** [comment]
...which in turn boils down to the fact the Executable::FindFunction(name) call returns the last function defined with that name. Any code that uses FindFunction(name) thus may have a problem in the presence of overloaded functions with the requested name.
