### ISSUE TITLE
[VM] Inapropriate default/general impl. of object hash (`Object::GetHashCode()`) 

### ISSUE THREAD

**Issue by pbukva** [fetchai/ledger#1211]
The current general implementation of the Object hash is incorrect since it is *not* derived from _value_ which instance of reference type represents, but instead it is derived from _pointer_ to Object instance.

Implication is that primary property of hash is lost - hash value must be the same for two distinct instances which equal by _value_ (if `value1 == value2` then following must be true `hash(value1) == hash(value2)`), what however is not the case (in general) in the current implementation.

As things stands now, only the `String` type overrides & properly implements the `GetHashCode()` method, all other reference types (`Address`, `Array<...>`, `Map<...>`) fall back to default implementation from `Object` type.

As by now, the main impact is on `Map<...>` type, where elements of map can't be retrieved by key value if key type is any reference type but String -  for example, code sample bellow will fail to find the element (please be aware that another _independent_ issue interferes here - the _equality_ operator for Array is _not_ implemented yet, however even if it would be, the sample code bellow will fail because of hash issue):
```JS
function main()
    var a = Array<String>(1);
    a[0] = "Hello World!";

    var b = Array<String>(1);
    b[0] = "Hello World!";
   
    var m = Map<Array<String>, String>();
    m[a] = "a value";
    
    //This should print "a value", but instead it fails on "map key does not exist" error.
    //The essential thing here is that we use the `b` key here to retrieve the value
    printLn(m[b]);
endfunction
```

Suggested solution:
 * Change the default implementation of `Object::GetHashCode()` so that it would raise `RuntimeError(std::string(__func__) + "function not implemented")`
 * Properly override & implement `GetHashCode()` method in all remaining Object based types where it is not done yet (`Address`, `Array<...>`, `Map<...>`).

**Comment by robertdickson** [comment]
The current implementation, for reference types besides String, defaults to hashing the stored pointer and does reference equality on those stored pointers, which is entirely correct. The m[b] above fails, rightly, because a and b arrays do not point to the same object.
*If* you want value equality on Arrays and Maps, which is a big if, then override GetHashCode() and IsEqual() as is done for String.

**Comment by robertdickson** [comment]
I personally think that value equality on deeply nested structures like arrays and maps is a bad idea. but others may have a different perspective on this.

**Comment by robertdickson** [comment]
Address should support value equality though.
