### ISSUE TITLE
Ledger docs read.me

### ISSUE THREAD

**Issue by dishmop** [fetchai/ledger#1293]
Cannot build the documentation on osx.

(venv3) Diarmids-MacBook-Pro:docs diarmidcampbell$ pip3 install sphinxcontrib.mermaid watchdog
Collecting sphinxcontrib.mermaid
  Using cached https://files.pythonhosted.org/packages/b8/8d/3b3eaf71c03bea7308de8e646616e9536a44280d1250c642cbb87c118aba/sphinxcontrib_mermaid-0.3.1-py2.py3-none-any.whl
Requirement already satisfied: watchdog in /Users/diarmidcampbell/Projects/ledger/venv3/lib/python3.7/site-packages (0.9.0)
Requirement already satisfied: argh>=0.24.1 in /Users/diarmidcampbell/Projects/ledger/venv3/lib/python3.7/site-packages (from watchdog) (0.26.2)
Requirement already satisfied: pathtools>=0.1.1 in /Users/diarmidcampbell/Projects/ledger/venv3/lib/python3.7/site-packages (from watchdog) (0.1.2)
Requirement already satisfied: PyYAML>=3.10 in /Users/diarmidcampbell/Projects/ledger/venv3/lib/python3.7/site-packages (from watchdog) (5.1.1)
Installing collected packages: sphinxcontrib.mermaid
Successfully installed sphinxcontrib.mermaid
(venv3) Diarmids-MacBook-Pro:docs diarmidcampbell$ ./generate.py 
Building documentation...
Running Sphinx v1.7.9

Extension error:
Could not import extension sphinxcontrib.mermaid (exception: No module named mermaid)
Traceback (most recent call last):
  File "./generate.py", line 87, in <module>
    main()
  File "./generate.py", line 69, in main
    build_documentation()
  File "./generate.py", line 38, in build_documentation
    subprocess.check_call(cmd, cwd=DOCUMENTATION_ROOT)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sphinx-build', '-M', 'html', 'source', 'build']' returned non-zero exit status 2.
(venv3) Diarmids-MacBook-Pro:docs diarmidcampbell$

**Comment by ejfitzgerald** [comment]
Documentation updated and moved to new repo.
