### ISSUE TITLE
Ditch Node convenience constructor

### ISSUE THREAD

**Issue by baykaner** [fetchai/ledger#1476]
Node has a constructor for constructing nodes by specifying only the Op type Enum; this allows slightly more concisely written tests in a few places, but the price for this is:

- another switch-case to maintain in Node, and
- unnecessary includes inside node.hpp 

and this cannot be scaled to include layers (because of the circular dependency that would create).

We should remove this constructor and rewrite those few tests as necessary

**Comment by evsmithx** [comment]
Fixed by #1493
