### ISSUE TITLE
ml placeholder SetData does not make a deep copy

### ISSUE THREAD

**Issue by baykaner** [fetchai/ledger#1488]
this is fast but unsafe for users writing applications - if they later modify the tensor after calling 
graph.SetInput("node_name", tensor); this will modify the internal state of the placeholder data.

Therefore we should make a safe method (for users to set data manually), and a fast method (for the optimiser to use)

**Comment by MissingNO57** [comment]
Closed by #1693

**Comment by evsmithx** [comment]
Closed by #1695
