### ISSUE TITLE
Graph SetRegularisation needs reworking

### ISSUE THREAD

**Issue by evsmithx** [fetchai/ledger#1553]
Graph ApplyRegularisation is called on the weights while backpropagating the error, which is not always the right place for it. ApplyRegularisation should actually increment a separate regularisation_accumulation matrix (like gradient_accumulation) which gets applied along with the gradient.

Also SGDOptimiser doesn't apply regularisation at all. Other optimisers should be checked too.

**Comment by MissingNO57** [comment]
Closed by #1693
