### ISSUE TITLE
`VerifiedTransaction::Create(...)` methods ignore verification result

### ISSUE THREAD

**Issue by pbukva** [fetchai/ledger#189]
Verification result is ignored inside of the  `VerifiedTransaction::Create(...)` methods.
This can result to creation of valid `VerifiedTransaction` instance in the case when it's internal data fail verification, what directly contradict the sole purpose/ideology of the `VerifiedTransaction` class.

**Comment by bipll** [comment]
Currently, `Create()` is called from transaction_verifier.cpp which checks for success. Other uses are from tests and benchmarks, less critical.
