### ISSUE TITLE
Build error at target bn_c256_test (Ubuntu 18.04)

### ISSUE THREAD

**Issue by Kevin-Chen0** [fetchai/ledger#2239]
I am following the Fetch [Quickstart](https://docs.fetch.ai/getting-started/quickstart/) docs of installing the latest ledger: https://docs.fetch.ai/getting-started/quickstart/ 

However, it keeps on failing on this point:

```
[ 42%] Building C object vendor/openssl/crypto/CMakeFiles/crypto.dir/x509v3/v3_tlsf.c.o
[ 42%] Building C object vendor/openssl/crypto/CMakeFiles/crypto.dir/x509v3/v3err.c.o
[ 42%] Building C object vendor/openssl/crypto/CMakeFiles/crypto.dir/x509v3/v3_utl.c.o
[ 42%] Building C object vendor/openssl/crypto/CMakeFiles/crypto.dir/threads_pthread.c.o
[ 43%] Linking C static library libcrypto.a
[ 43%] Built target crypto
[ 43%] Linking CXX executable ../../bin/bn_c256_test
[ 43%] Built target bn_c256_test
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Error: failed on line 50.
```
Should I try out a downgraded version of the ledger instead, as noted in the doc? **release/v0.9.x**

Thanks.

**Comment by Kevin-Chen0** [comment]
I have found someone having a somewhat similar build Issue with EOS, although the solutions proposed there didn't work out for me:

https://github.com/EOSIO/eos/issues/6650

**Comment by wkaluza** [comment]
Contrary to the issue title, the included log snippet clearly states that `bn_c256_test` was built successfully. The actual error was probably described further up; we may never know.
