### ISSUE TITLE
Implement FixedPoint math operators +/-* without casting

### ISSUE THREAD

**Issue by baykaner** [fetchai/ledger#501]
in order for FixedPoint type to be safe from rounding errors (i.e. always hashes the same for on all architectures), it's math operators must have native implementations that do not cast to unsafe types (e.g. double/float).

**Comment by markos** [comment]
can this be considered fixed?

**Comment by markos** [comment]
closing this, as FixedPoint doesn't use casting to unsafe types anymore for most operations.
