### ISSUE TITLE
Clear up common functions

### ISSUE THREAD

**Issue by n-hutton** [fetchai/ledger#524]
There is replicated common functionality, such as functions to create transactions in bulk, random numbers, timers etc. There should be a namespace for these which tests and main code can include.

**Comment by ejfitzgerald** [comment]
@n-hutton this is quite a top level issue can you break this down into a few specific issues that you were thinking about (and close this issue)

**Comment by ejfitzgerald** [comment]
This is quite vague @n-hutton if you get chance can you raise specific examples
