### ISSUE TITLE
Fix Fixed Point CheckNoRounding

### ISSUE THREAD

**Issue by pierre-wilmot-fetch-ai** [fetchai/ledger#629]
Current implementation is wrong

**Comment by pierre-wilmot-fetch-ai** [comment]
@markos This is an old isue I oppened 3 months ago when I looked at the FixedPoint class for the first time. Please close it when you feel the problem is solved 😄 

That about the base10 vs base 2 comparaison for number of digit in the fractional part

**Comment by markos** [comment]
I provided now a working CheckNoRounding() in  #968 ,  but there is a catch. Almost always there is a rounding error and if we use assert(CheckNoRounding()) it won't go far in execution.
