### ISSUE TITLE
Implement convolution as im2col + GEMM

### ISSUE THREAD

**Issue by pierre-wilmot-fetch-ai** [fetchai/ledger#699]
Since the current implementation of Matrix multiplication is slow and naive, I'm not gonna use it for convolutions. So I'm doing convolutions in a slow and naive way too.

When we get a proper vectorised GEMM, we can make the switch to a better implementation forn convolution.

https://petewarden.com/2015/04/20/why-gemm-is-at-the-heart-of-deep-learning/

**Comment by pierre-wilmot-fetch-ai** [comment]
Or may be worth looking in that one too : https://arxiv.org/pdf/1704.04428.pdf

**Comment by MissingNO57** [comment]
I finished implementation of GEMM forward pass for 2D convolution, I will also try to make Backward pass in GEMM way.

See PR #883
