### ISSUE TITLE
Fix issue still pending object promises

### ISSUE THREAD

**Issue by ejfitzgerald** [fetchai/ledger#750]
Seeing a lot of the following messages from the test net

```
Lane 0: Still pending object promises but limit approached!
Lane 0: Still pending object promises but limit approached!
Lane 0: Still pending object promises but limit approached!
Lane 0: Still pending object promises but limit approached!
```

**Comment by ejfitzgerald** [comment]
@n-hutton this appears quite alot on the mining node on the test net. I suspect that this might be pointing towards the fact that muddle might not be cleaning up all pending promises in the dispatch register. (If this is the case it might be related to #792 to).

**Comment by n-hutton** [comment]
Looks like I fixed an unrelated issue of a segfault in muddle when testing this. You mentioned in the standup that it could be replicated by a client disconnecting during syncing. I think when I tested this the client would segfault at some point which could make the message appear
