### ISSUE TITLE
Zip implementation for tensor

### ISSUE THREAD

**Issue by baykaner** [fetchai/ledger#804]
Throughout the math library we often want to use the tensor iterator to quickly index multiple tensors of the same size. At the moment we have to do it like this:

SizeType idx{0};
for (auto &val : array1)
{
    ret += (val + array2.At(idx));
}

but it would be better if we could do something like this:
for (auto &i  : Tensor::Zip(array1, array2))
{
    ret += (i.get<0>() + i.get<1>());
}

**Comment by MissingNO57** [comment]
Tensor iterators covers this
