### ISSUE TITLE
VM: Common Array options

### ISSUE THREAD

**Issue by ejfitzgerald** [fetchai/ledger#812]
The following should be possible when working with arrays:

### Initialisation
```c#

// value initialisation
var arr = [1,2,3,4]; // should deduce an array 4 element array with type of Int32

// range initialisation
var arr = [1u; 5]; // should decude an array of 5 elements all set with the value 1 and of type UInt32
```

### Appending / Removal (Back)

```c#
var arr = [1,2,3,4];

// add the value 5 to the array
arr.append(5); // now should contain [1,2,3,4,5]

// remove a value from the array
var result1 = arr.pop_back(); // no args mean size 1, arr = [1,2,3,4], result1 = 5

// removal of multiple values
var result2 = arr.pop_back(2); // remove multiple elements arr = [1,2], result2 = [3,4]

// extending of array
arr.extend([1,2,3]); // arr = [1,2,1,2,3]

```

### Corresponding Queue like functionality

```c#
var arr = [1,2,3,4];

// remove a value from the array
var result1 = arr.pop_front(); // no args mean size 1, arr = [2,3,4,5], result1 = 1

// removal of multiple values
var result2 = arr.pop_front(2); // remove multiple elements arr = [4,5], result2 = [2,3]
```

**Comment by bipll** [comment]
> `var arr = [1u; 5];`

Doesn't look very intuitive. How about Perl-style `[1u x 5]`, or, say, more distinct `[5 of 1u]`?

**Comment by ejfitzgerald** [comment]
@bipll I am planning on getting @wkaluza to add the `pop_front()`, `pop_back()`, and `append()` methods. I will leave the initialisation for you or @robertdickson

**Comment by bipll** [comment]
@ejfitzgerald Ok, I will probably implement inits some time later this week.

**Comment by wkaluza** [comment]
Reopening, as closed by mistake.

**Comment by wkaluza** [comment]
Closing as only partially in progress. @bipll pleasue use JIRA issue LDGR-321 for tracking the initialisation part of this work.

**Comment by bipll** [comment]
Ok, will do.

**Comment by bipll** [comment]
@wkaluza Btw what's a JIRA issue in this particular case?

**Comment by wkaluza** [comment]
@bipll we're in the process of moving our issue tracking away from GitHub Issues to JIRA. Link to the issue in question is here: https://fetchai.atlassian.net/browse/LDGR-321 (log in using Fetch.AI Google credentials).

As far as I know, JIRA issues are not linked to GitHub PRs directly, so one immediate immediate consequence is that we need to manually mark them as Done (dropdown on the right in the link), rather than use "Closes #xyz" in the PR.

**Comment by bipll** [comment]
> As far as I know, JIRA issues are not linked to GitHub PRs directly

Hm.
https://confluence.atlassian.com/jirasoftwarecloud/referencing-issues-in-your-development-work-777002789.html
Worth to be tried imo.
