### ISSUE TITLE
Implement general Setter with variadic for Tensor

### ISSUE THREAD

**Issue by baykaner** [fetchai/ledger#857]

**Comment by baykaner** [comment]
interface like this:
template< typename ... Indices >
void Set(Indices ... indices, Type &val)
{
}

**Comment by bipll** [comment]
@baykaner Will it even compile, a value after a pack?

**Comment by baykaner** [comment]
The interface, from the user's perspective, needs to ACT as though it is as specified above. 
The actual interface will look like this:
template <typename ... Args>
void Set(Args ... args)
{
}
but behave as described previously.
You can see the implementation when I close this issue later this week
