### ISSUE TITLE
Diamond shaped ops graph cannot be evaluated

### ISSUE THREAD

**Issue by MissingNO57** [fetchai/ledger#916]
Diamond shaped graph cannot be evaluated.

Example:
tmp1=input+input
tmp2=input+input
output=tmp1+tmp2

Attached code that can be used for reproduction:
[diamond.zip](https://github.com/uvue-git/fetch-ledger/files/3127534/diamond.zip)

**Comment by pierre-wilmot-fetch-ai** [comment]
Relates to #890
