### ISSUE TITLE
Integration tests occasionally fail on develop

### ISSUE THREAD

**Issue by n-hutton** [fetchai/ledger#929]
Looking back through the recent develop builds, I notice the following SLOW integration tests failing:

```
5x network_gtest
1x containers-tests
```

- [ ] #519 -  `network_gtest`
- [ ] #561 - `exectors_gtest`
- [ ] #944 - `containers-tests`
- [ ] #945 - `muddle_gtests`

These are flaky - this should be addressed

**Comment by wkaluza** [comment]
I've just had muddle_gtest time out on me in a PR branch. I replayed the run and it was fine.

**Comment by ejfitzgerald** [comment]
> I've just had muddle_gtest time out on me in a PR branch. I replayed the run and it was fine.

I have also seen this too
